#!/usr/bin/env python3
"""
make_readme.py -- regenerate the results section of README.md from the current
projections, so the numbers in the repo are never stale relative to data/.

    python3 make_readme.py

Rewrites everything between the RESULTS:START and RESULTS:END markers. Run it
after project.py; run build_hosted.py separately if you want a refreshed
single-file page.
"""

from __future__ import annotations

import csv
import os

PROJ = os.path.join("data", "projections_2026_27.csv")
README = "README.md"
START, END = "<!-- RESULTS:START -->", "<!-- RESULTS:END -->"
PAGES = ("https://ajfroster.github.io/2026-2027-NHL-fantasy-prep-tool/"
         "dashboard.html")
TIER_ORDER = ["S++", "S+", "S", "A", "B", "C", "D"]
TOP_N = 25


def load() -> list[dict]:
    with open(PROJ, newline="", encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh))
    for r in rows:
        for k in ("gp_proj", "fppg_default", "fantasyPoints_default",
                  "vorp_default", "vorpPG_default", "replacement_baseline",
                  "replacement_fppg"):
            r[k] = float(r[k]) if r[k] else 0.0
    return rows


def board(rows: list[dict]) -> str:
    top = sorted(rows, key=lambda r: -r["fppg_default"])[:TOP_N]
    out = ["| # | Player | Pos | Team | Tier | GP | FPPG | Total | VORP | VORP/G |",
           "|--:|---|:-:|:-:|:-:|--:|--:|--:|--:|--:|"]
    for i, r in enumerate(top, 1):
        out.append(f"| {i} | {r['playerName']} | {r['position']} | {r['team']} | "
                   f"{r['tier_default']} | {r['gp_proj']:.1f} | "
                   f"{r['fppg_default']:.2f} | {r['fantasyPoints_default']:.1f} | "
                   f"{r['vorp_default']:+.1f} | {r['vorpPG_default']:+.2f} |")
    return "\n".join(out)


def tiers(rows: list[dict]) -> str:
    out = ["| Tier | Forwards | F FPPG range | Defensemen | D FPPG range |",
           "|:-:|--:|:-:|--:|:-:|"]
    for t in TIER_ORDER:
        cells = []
        for pg in ("F", "D"):
            sub = [r for r in rows if r["positionGroup"] == pg
                   and r["tier_default"] == t]
            if sub:
                lo = min(r["fppg_default"] for r in sub)
                hi = max(r["fppg_default"] for r in sub)
                cells += [str(len(sub)), f"{lo:.2f}–{hi:.2f}"]
            else:
                cells += ["—", "—"]
        out.append(f"| **{t}** | {cells[0]} | {cells[1]} | {cells[2]} | {cells[3]} |")
    return "\n".join(out)


def build_section(rows: list[dict]) -> str:
    f = next(r for r in rows if r["positionGroup"] == "F")
    d = next(r for r in rows if r["positionGroup"] == "D")
    n_f = sum(1 for r in rows if r["positionGroup"] == "F")
    n_d = len(rows) - n_f
    return f"""{START}
<!-- Generated by make_readme.py -- edit that script, not this block. -->

## The projections

**[Open the interactive dashboard]({PAGES})** — sortable, filterable, and every
number recomputes live when you change the scoring weights. No install, no
server; it runs entirely in the browser off the CSVs in `data/`.

[![NHL fantasy projections dashboard](docs/dashboard.png)]({PAGES})

Click any row to expand a player's three actual seasons beside the projection,
with per-60 rates, ice time, and the multipliers that produced the forecast:

![Per-player breakdown](docs/player-detail.png)

### Top {TOP_N} for 2026-27

At the default scoring below, ranked by projected fantasy points per game.
{len(rows)} skaters are projected in total ({n_f} F, {n_d} D).

{board(rows)}

### Tiers

S++ is the top 12 players overall by projected season total — the first round of
a 12-team draft. S+ through D come from 1-D k-means on projected FPPG, computed
separately for each position group, so the breaks land on real gaps in the pool
rather than on round-number percentiles. Players projected under 40 games are
unranked.

{tiers(rows)}

Replacement level in a 12-team league starting 9 F and 4 D:
**{f['replacement_baseline']:.1f} points ({f['replacement_fppg']:.2f} per game)**
for forwards, **{d['replacement_baseline']:.1f} points
({d['replacement_fppg']:.2f} per game)** for defensemen. VORP and VORP/G are
measured against those, and both move when you change the league shape.

### Default scoring

| Goal | Assist | Shot on goal | Hit | Blocked shot |
|--:|--:|--:|--:|--:|
| 2.0 | 1.5 | 0.15 | 0.2 | 0.35 |

These are only the defaults. Weights are never baked into the projections —
`project.py` writes projected stat totals and the interfaces apply whatever
scoring you set, recomputing FPPG, totals, VORP, VORP/G and every tier on the
spot.

{END}"""


def main() -> int:
    rows = load()
    with open(README, encoding="utf-8") as fh:
        text = fh.read()
    section = build_section(rows)
    if START in text and END in text:
        head, rest = text.split(START, 1)
        _, tail = rest.split(END, 1)
        text = head + section + tail
    else:
        anchor = "\n## Run\n"
        if anchor not in text:
            raise SystemExit("could not find the '## Run' heading to insert before")
        text = text.replace(anchor, "\n" + section + "\n" + anchor, 1)
    with open(README, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"README results section rebuilt from {len(rows)} projections.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
